// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM4tCHB01mQXclUU_hPG96y3iqPci59ME',
    appId: '1:704997853642:web:8ebdd853313d361813a733',
    messagingSenderId: '704997853642',
    projectId: 'ghost-smartgreenhouse',
    authDomain: 'ghost-smartgreenhouse.firebaseapp.com',
    databaseURL: 'https://ghost-smartgreenhouse-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ghost-smartgreenhouse.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYHLCmlWCQELpz-v9_aWUKlQaMgZw9Zdo',
    appId: '1:704997853642:android:c8d9c08c5cd1436e13a733',
    messagingSenderId: '704997853642',
    projectId: 'ghost-smartgreenhouse',
    databaseURL: 'https://ghost-smartgreenhouse-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ghost-smartgreenhouse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5BKnZ9L2Nb255U2dVrZrLY_yPppgIz7Q',
    appId: '1:704997853642:ios:cf19bc2dc0c437cf13a733',
    messagingSenderId: '704997853642',
    projectId: 'ghost-smartgreenhouse',
    databaseURL: 'https://ghost-smartgreenhouse-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ghost-smartgreenhouse.firebasestorage.app',
    iosBundleId: 'com.example.smartgreenhouse',
  );
}
